server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker container logs with service discovery
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Keep only containers that have logs
      - source_labels: [__meta_docker_container_log_stream]
        regex: .+
        action: keep
      
      # Add container name as label
      - source_labels: [__meta_docker_container_name]
        regex: "/(.+)"
        target_label: container_name
      
      # Add compose service name as label
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service
      
      # Add compose project name as label
      - source_labels: [__meta_docker_container_label_com_docker_compose_project]
        target_label: project
      
      # Add container image as label
      - source_labels: [__meta_docker_container_image]
        target_label: image
      
      # Set the log file path
      - source_labels: [__meta_docker_container_log_stream]
        target_label: __path__

    pipeline_stages:
      - json:
          expressions:
            stream: stream
            attrs: attrs
            tag: attrs.tag
            time: time
      - labels:
          stream:
          tag:
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: log
