global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'

  # Loki
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    metrics_path: '/metrics'

  # Jaeger
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:16686']
    metrics_path: '/metrics'

  # Promtail
  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']
    metrics_path: '/metrics'

  # Example microservice - replace with your actual service
  - job_name: 'auth-service'
    static_configs:
      - targets: [ 'localhost:8100' ]
    metrics_path: '/prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s
    # Add labels for better identification
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace

  # Docker containers with exposed metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Node Exporter (if you want system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 30s 
