apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: true
    jsonData:
      httpMethod: GET
      defaultQuery:
        service: ""
        operation: ""
        tags: ""
        minDuration: ""
        maxDuration: ""
        limit: 20 